### ISSUE TITLE
Remove single-country companies

### ISSUE THREAD

**Issue by yanirs** [yanirs/established-remote#104]
With #102, we will have information about where each company is hiring from. To make the list more globally-relevant, it should exclude companies that hire from a single country.

**Comment by abuuzayr** [comment]
Makes sense! There a plenty of US companies offering US only remote positions, a bit too many for this list.

**Comment by yanirs** [comment]
@abuuzayr Yep, the list has also grown a bit too large, so if you're up to contributing to #103 and #105 as well, it'd be very welcome!
