### ISSUE TITLE
Coinbase, Shopify, Slack, Square and Twitter

### ISSUE THREAD

**Issue by Kerl1310** [yanirs/established-remote#139]
[Coinbase](https://blog.coinbase.com/post-covid-19-coinbase-will-be-a-remote-first-company-cdac6e621df7?gi=e34fafb9aff3), [Shopify](https://www.fool.com/investing/2020/05/22/shopify-is-going-all-in-on-remote-work.aspx), [Slack](https://mashable.com/article/slack-remote-work-permanent-coronavirus/?europe=true), [Square](https://www.cnbc.com/2020/05/18/square-lets-employees-work-from-home-permanently.html#:~:text=Both%20of%20Jack%20Dorsey's%20companies,would%20have%20the%20same%20option.) and [Twitter](https://techcrunch.com/2020/05/12/twitter-says-staff-can-continue-working-from-home-permanently/?guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_sig=AQAAAE8GSTjz9S45_SSSiW1OP5G_tZbAEKDBKRuvsuDItmRqf_CTfooqTgTQBXJzBu6q4reTb9XD8PK14pOaLl35KDmwqvHinxfDNhBvFGGGt3hApVBRJ19jQ_geawd9TkyEsFXmxc9Lwh8py2-us0LP3eXkWFFYSj3BHMxznMOjZoYR) have all recently announced the move to either entirely remote or majority remote.

**Comment by yanirs** [comment]
Happy to add them when they update their job pages to match their announcements. :slightly_smiling_face:

**Comment by uxdmitryn** [comment]
Shopify already has. https://www.shopify.ca/careers/search?keywords=&sort=specialty_asc
