### ISSUE TITLE
Add time zones and overlap information

### ISSUE THREAD

**Issue by ajayvigneshk** [yanirs/established-remote#145]
The `anywhere` label used by companies is quite misleading as most of them also require significant hours of overlap with a particular time zone.

**Comment by yanirs** [comment]
Thanks @ajayvigneshk! I think this should be covered by the current column. For example, there's already one case of `Anywhere with at least 4 hrs overlap over EU time zone`. If you find similar companies, it'd be great if you could push a PR changing `Anywhere` to `Anywhere between UTC-XX and UTC+YY`, or something along these lines. :slightly_smiling_face:

**Comment by yanirs** [comment]
A format like `Anywhere with X hours overlap with <timezone>` also works. :slightly_smiling_face:

**Comment by ajayvigneshk** [comment]
Ah! Just now seeing it. Makes sense
