### ISSUE TITLE
Auth0 hires remotely in only 6 nations not counting Europe and North America.

### ISSUE THREAD

**Issue by yashjaiswal** [yanirs/established-remote#148]
As of 18 Sept, Auth0's career page shows hiring only for 6 nations outside of Europe and North America.
[https://auth0.com/careers/positions?areas=Engineering](url)

**Comment by yanirs** [comment]
Thanks @yashjaiswal. Where do you see that?

**Comment by yanirs** [comment]
Auth0 is no longer on the list :slightly_smiling_face:
