### ISSUE TITLE
Adding Quora to the list

### ISSUE THREAD

**Issue by mojpm** [yanirs/established-remote#159]
![quora](https://user-images.githubusercontent.com/70036189/103438319-2ad42c80-4c43-11eb-8717-361f17c58d4f.png)

Recently Quora announced that starting June 2020 it would be a remote-first company which can also be found on their official website.
Does this qualify it for the list? If so, may I create a pull request for it?

**Comment by yanirs** [comment]
Thanks @mojpm! Given Quora's timezone availability requirement (business hours in PST), I'd say that they're only targeting employees in the Americas, so they don't fit this criterion:

> To make this list more useful to a global audience, companies that don't hire engineers across multiple timezone regions are no longer included. The timezone regions are roughly: Americas, Europe-Africa, and Asia-Pacific.
