### ISSUE TITLE
I suggest adding Upwork.com

### ISSUE THREAD

**Issue by kikianion** [yanirs/established-remote#222]
I think adding upwork.com is relevant to the current list, or is it any reason not to add this remote working directory site?

![image](https://github.com/yanirs/established-remote/assets/11998096/1583d3f2-97c3-4912-b0d3-8dca7854325c)

**Comment by yanirs** [comment]
Thanks @kikianion. The focus on the list is on remote tech companies rather than on freelancing sites, of which there are many. [Upwork the company only hires in the US](https://www.upwork.com/careers/jobs/explore), so it's not a good a fit under the current criteria.
