### ISSUE TITLE
Request to add a new site

### ISSUE THREAD

**Issue by Nithur-M** [yanirs/established-remote#234]
Hey @yanirs,
RemoteBase dot com is more of a talent matching site than remote job search site. Can I add another remote job search site instead of RemoteBase?
Link: https://www.realworkfromanywhere.com/

Thanks.

**Comment by yanirs** [comment]
Thanks @Nithur-M, but the primary goal of the list is for actual companies, not aggregators.

**Comment by Nithur-M** [comment]
Thanks @yanirs.

I see that you listed having more traffic as a prerequisite to adding a job board to the list. The site I mentioned above has more traffic than another job board (okjob) listed in the repo. 
[Traffic of Okjob.io](https://www.similarweb.com/website/okjob.io/#ranking)
[Traffic of RealWorkFromAnyhwere](https://www.similarweb.com/website/realworkfromanywhere.com/#traffic)

**Comment by yanirs** [comment]
Fair point, but I made an exception there because of the four-day workweek: https://github.com/yanirs/established-remote/pull/227#issuecomment-1819986889

**Comment by Nithur-M** [comment]
Got it.

Tbh, Real Work From Anywhere is the only job board that supports location independence. All the jobs on the site are 100% globally remote for global talent to find remote opportunities. Big remote job sites are mostly filled with location restricted  remote jobs, for example- remote US only.

Also, Real Work From Anywhere has more traffic than another job site on the list (Remote4me).
[Traffic of Remote4me](https://www.similarweb.com/website/remote4me.com/#overview)
[Traffic of RealWorkFromAnywhere](https://www.similarweb.com/website/realworkfromanywhere.com/#overview)

**Comment by yanirs** [comment]
Fair points. I did change the focus of the list to be on globally-accessible remote work.
Alright, if you add a PR to add RealWorkFromAnywhere I'll approve it. :slightly_smiling_face:
