### ISSUE TITLE
Request to add new companies

### ISSUE THREAD

**Issue by M-AminAlizadeh** [yanirs/established-remote#237]
Hello there
Check out these companies:

- [ShakaCode](https://www.shakacode.com/) -- stacks: React / Rails
- [Nextcloud](https://nextcloud.com/jobs) -- stacks: JS(Vue) / PHP(Laravel)

**Comment by yanirs** [comment]
Thanks @M-AminAlizadeh. Please feel free to open a PR if the companies meet the criteria of the list.

**Comment by M-AminAlizadeh** [comment]
@yanirs I did: https://github.com/yanirs/established-remote/pull/238
