### ISSUE TITLE
Request to add a new remote jobs board

### ISSUE THREAD

**Issue by oter** [yanirs/established-remote#239]
Hi @yanirs 

I would like to add my remote jobs board to the "Remote job search websites" section
Link: https://jobscollider.com/remote-jobs

I scan 10,000+ companies every day to gather all open jobs, classify each job, filter for remote positions, and post them on my site:  https://x.com/oterpr/status/1814711719392076223

Currently, there are around 30,000 live remote jobs, and traffic is constantly increasing: https://x.com/oterpr/status/1822375021458641312

I hope you'll consider giving it a chance :) 
Thanks,
Max

**Comment by yanirs** [comment]
Thanks Max, but as noted on the readme, the sample of job boards is already enough. :slightly_smiling_face:
