### ISSUE TITLE
Datastax new URL

### ISSUE THREAD

**Issue by pnhatminh** [yanirs/established-remote#95]
[Here](https://datastax.wd5.myworkdayjobs.com/DataStaxCareers/jobs) is the new URL for Datastax. The previous one would lead to a 404 page

**Comment by yanirs** [comment]
Thanks @pnhatminh! I updated the link in https://github.com/yanirs/established-remote/commit/881797c577300cc125f9fd3d9b849667359b1c5b. In the future, feel free to open a PR with proposed changes.
